---
title: "Additional Information"
subtitle: |
  | Final Project 
  | STAT 302
author: "Lily Ng"

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---

#### What is the core concept(s) or insight(s) into the data that you believe the visualization communicates?

This visualization led me to two insights. First is that race is correlating factor in what percentage of students end up meeting benchmark standards. The second is that the pandemic had an impact on scores. For the first insight, toggling through the different data we can see that schools with primarily Asian or White makeup meet standards significantly more than their Black and Hispanic peers. There is around a 20% gap of students being on target between Asian and White students versus Hispanic and Black students, whether it be ELA or Math scores. This is following the general well known trend in education where Black and Brown students tend to have a gap in their data as opposed to their White and Asian peers, for reasons that can be tracked to a variety of factors, such as opportunity, socioeconomic status, racism, etc. In the second insight, we see a drop in percentage of students meeting ELA and Math scores post pandemic. We can see a slight gain in scores from one year out from the pandemic, but on average students have not yet performed at the levels they were pre-pandemic. The only racial group that defies this trend is the ELA scores for primarily Asian schools, where there is a steady gain of students meeting ELA levels. In the data set, there are very few schools that are primarily Asian, which means that each school has a lot more pull over the data as compared to the larger pool of data for majority Black and Hispanic schools. Overall, the interactive visualization shows that race and the pandemic are generally correlative factors for students meeting ELA and Math standards

*Note on data: I found the primary racial group at each school (found the proportions of each racial group and picked the highest one), and then took the averages from each racial group by year. Because of the way the data is set up, it made the most sense to manipulate the data first and then plot it as opposed to making it a part of my graphs.*

*On data syntax: I used racial groupings based on what was provided in the data. I choose the two years closest to pre and post pandemic, so there was no data available online for any school year that involved 2020. The year labels at the bottom of each graph signify the year the test was taken, which is in the spring. Therefore '2023' represents school year 2022-23.*

#### Explain your choice of widgets and what about the data it help users understand.

I chose to make widgets based on majority racial group as well as subject of test. I chose ELA versus Math scores because the tests are tracked separately, therefore they should be viewed separately. As for my choice to divide by racial groups, we know that the identity of race can have societal impacts on people's lives. If we looked at the trends in the data as just one general trend without subdividing by race, we would likely miss that racial group has different correlative trends for scores. If we cannot see that, we will likely not know where to apply equitable resources for students, and will have a general lack of understanding for the students based on who they are as individuals.
